# Generated by Django 3.0.6 on 2020-11-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_blogging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogging',
            old_name='image',
            new_name='img',
        ),
    ]
