# Generated by Django 3.0.6 on 2020-11-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201104_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media/users/newindex.png', null=True, upload_to='media/users'),
        ),
    ]
