# Generated by Django 3.0.6 on 2020-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media/users/newindex.png', null=True, upload_to='media/users'),
        ),
    ]
