# Generated by Django 3.0.6 on 2020-11-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_blogging_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
