# Generated by Django 3.0.6 on 2020-11-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201112_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogging',
            name='slug',
        ),
    ]
