# Generated by Django 3.0.6 on 2020-11-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_blogging_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogging',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
